#ifndef COMMONSSPLTYPES_H
#define COMMONSSPLTYPES_H

#include <c_base.h>
#include <c_misc.h>
#include <c_sync.h>
#include <c_collection.h>
#include <c_field.h>
#include <v_copyIn.h>

#include "Commons_DCPS.hpp"


extern c_metaObject __Commons_Mind__load (c_base base);

extern c_metaObject __Mind_HouseMode__load (c_base base);
enum _Mind_HouseMode {
    _Mind_HOUSE_MODE_AWAY,
    _Mind_HOUSE_MODE_HOLIDAY,
    _Mind_HOUSE_MODE_DAY,
    _Mind_HOUSE_MODE_NIGHT,
    _Mind_HOUSE_MODE_GUEST,
    _Mind_HOUSE_MODE_SETUP
};

extern c_metaObject __Mind_TemperatureMode__load (c_base base);
enum _Mind_TemperatureMode {
    _Mind_TEMPERATURE_MODE_NONE,
    _Mind_TEMPERATURE_MODE_SUMMER,
    _Mind_TEMPERATURE_MODE_WINTER
};

extern c_metaObject __Mind_NotificationSetting__load (c_base base);
enum _Mind_NotificationSetting {
    _Mind_SECURITY_NOTIFICATION_SETTING_NONE,
    _Mind_SECURITY_NOTIFICATION_SETTING_SNS_PLUS_LED,
    _Mind_SECURITY_NOTIFICATION_SETTING_SNS_PLUS_LED_PLUS_ALARM
};

extern c_metaObject __Mind_NightAlarmSetting__load (c_base base);
enum _Mind_NightAlarmSetting {
    _Mind_NIGHT_ALARM_SETTING_NONE,
    _Mind_NIGHT_ALARM_SETTING_FACE_RECOGNITION,
    _Mind_NIGHT_ALARM_SETTING_LOGIC,
    _Mind_NIGHT_ALARM_SETTING_VOLUMETRIC
};

extern c_metaObject __Mind_AmbienceType__load (c_base base);
enum _Mind_AmbienceType {
    _Mind_AMBIENCE_TYPE_ENTRANCE,
    _Mind_AMBIENCE_TYPE_CORRIDOR,
    _Mind_AMBIENCE_TYPE_LIVING_ROOM,
    _Mind_AMBIENCE_TYPE_DINING_ROOM,
    _Mind_AMBIENCE_TYPE_KITCHEN,
    _Mind_AMBIENCE_TYPE_PANTRY,
    _Mind_AMBIENCE_TYPE_BATHROOM,
    _Mind_AMBIENCE_TYPE_DRESSINGR_ROOM,
    _Mind_AMBIENCE_TYPE_BEDROOM,
    _Mind_AMBIENCE_TYPE_BEDROOM_CHILDREN,
    _Mind_AMBIENCE_TYPE_WARDROBE,
    _Mind_AMBIENCE_TYPE_CELLAR,
    _Mind_AMBIENCE_TYPE_GARAGE,
    _Mind_AMBIENCE_TYPE_TECHNICAL_ROOM,
    _Mind_AMBIENCE_TYPE_CATCHALL,
    _Mind_AMBIENCE_TYPE_UNDERSTAIRS,
    _Mind_AMBIENCE_TYPE_TERRACE,
    _Mind_AMBIENCE_TYPE_VERANDA,
    _Mind_AMBIENCE_TYPE_GYM,
    _Mind_AMBIENCE_TYPE_SPA,
    _Mind_AMBIENCE_TYPE_PLAYROOM,
    _Mind_AMBIENCE_TYPE_CINEMA,
    _Mind_AMBIENCE_TYPE_LAUDRY,
    _Mind_AMBIENCE_TYPE_OFFICE,
    _Mind_AMBIENCE_TYPE_CAVEAU,
    _Mind_AMBIENCE_TYPE_STAIRS,
    _Mind_AMBIENCE_TYPE_GARDEN
};

extern c_metaObject __Mind_SmartCommandType__load (c_base base);
enum _Mind_SmartCommandType {
    _Mind_SMART_COMMAND_LIGHTS,
    _Mind_SMART_COMMAND_SHUTTERS,
    _Mind_SMART_COMMAND_VENEZIANE,
    _Mind_SMART_COMMAND_SCURI,
    _Mind_SMART_COMMAND_GRATE,
    _Mind_SMART_COMMAND_MULTIMEDIA,
    _Mind_SMART_COMMAND_MUSICA,
    _Mind_SMART_COMMAND_TEMPERATURE,
    _Mind_SMART_COMMAND_WINDOWS,
    _Mind_SMART_COMMAND_POWER_CONSUMPTION
};

extern c_metaObject __Mind_StateName__load (c_base base);
enum _Mind_StateName {
    _Mind_STATE_SETUP,
    _Mind_STATE_AWAY,
    _Mind_STATE_HOLIDAY,
    _Mind_STATE_CHECKIN,
    _Mind_STATE_ALARMFROMNIGHT,
    _Mind_STATE_ALARMFROMCHECKIN,
    _Mind_STATE_DAY,
    _Mind_STATE_CHECKOUT,
    _Mind_STATE_CHECKOUT_GUEST,
    _Mind_STATE_CHECKOUT_HOLIDAY,
    _Mind_STATE_GUEST,
    _Mind_STATE_NIGHT
};

extern c_metaObject __Mind_Category__load (c_base base);
enum _Mind_Category {
    _Mind_CATEGORY_NONE,
    _Mind_CATEGORY_HOUSE,
    _Mind_CATEGORY_FLOOR,
    _Mind_CATEGORY_ROOM,
    _Mind_CATEGORY_AMBIENCE,
    _Mind_CATEGORY_MOBILE,
    _Mind_CATEGORY_HOUSE_TABLET,
    _Mind_CATEGORY_MIND_STREAMING,
    _Mind_MACRO_CATEGORY_AIR_CLEANING,
    _Mind_CATEGORY_AIR_CLEANING_VMC,
    _Mind_CATEGORY_AIR_CLEANING_CAPPAASPIRAZIONE,
    _Mind_CATEGORY_AIR_CLEANING_EXTRACTOR_FAN,
    _Mind_CATEGORY_LIGHT,
    _Mind_CATEGORY_LIGHT_DIMMABLE,
    _Mind_CATEGORY_LIGHT_DIMMABLE_FILTER,
    _Mind_CATEGORY_LIGHT_DIMMABLE_MIND,
    _Mind_CATEGORY_LIGHT_RGBW_MIND,
    _Mind_MACRO_CATEGORY_LIGHT_ALL,
    _Mind_MACRO_CATEGORY_LIGHT_INTERNAL,
    _Mind_MACRO_CATEGORY_LIGHT_EXTERNAL,
    _Mind_MACRO_CATEGORY_LIGHT_MAIN,
    _Mind_MACRO_CATEGORY_LIGHT_SOFT,
    _Mind_MACRO_CATEGORY_LIGHT_SERVICE,
    _Mind_MACRO_CATEGORY_LIGHT_STAIR,
    _Mind_CATEGORY_INPUT_SWITCH,
    _Mind_CATEGORY_INPUT_BUTTON,
    _Mind_CATEGORY_INPUT_SHUTTER_BUTTON,
    _Mind_MACRO_CATEGORY_INPUT,
    _Mind_CATEGORY_CONTACT_DOOR,
    _Mind_CATEGORY_CONTACT_WINDOW,
    _Mind_CATEGORY_CONTACT_TAMPER,
    _Mind_CATEGORY_CONTACT_PIR,
    _Mind_MACRO_CATEGORY_CONTACT,
    _Mind_MACRO_CATEGORY_SHUTTER,
    _Mind_MACRO_CATEGORY_EXTERNAL_SHUTTER,
    _Mind_CATEGORY_EXTERNAL_SHUTTER_ROLLER_SHUTTER,
    _Mind_CATEGORY_EXTERNAL_SHUTTER_SCURO,
    _Mind_CATEGORY_EXTERNAL_SHUTTER_FRANGISOLE,
    _Mind_MACRO_CATEGORY_INTERNAL_SHUTTER,
    _Mind_CATEGORY_INTERNAL_SHUTTER_BLINDS,
    _Mind_CATEGORY_INTERNAL_SHUTTER_VENEZIANA,
    _Mind_MACRO_CATEGORY_SECURITY_SHUTTER,
    _Mind_CATEGORY_SECURITY_SHUTTER_GRATA,
    _Mind_MACRO_CATEGORY_APPLIANCE,
    _Mind_CATEGORY_APPLIANCE_FORNO,
    _Mind_CATEGORY_APPLIANCE_FORNO_MICROONDE,
    _Mind_CATEGORY_APPLIANCE_FRIGO,
    _Mind_CATEGORY_APPLIANCE_FREEZER,
    _Mind_CATEGORY_APPLIANCE_CANTINA_VINI,
    _Mind_CATEGORY_APPLIANCE_MACCHINA_CAFFE,
    _Mind_CATEGORY_APPLIANCE_CAPPA,
    _Mind_CATEGORY_APPLIANCE_PIANO_COTTURA,
    _Mind_CATEGORY_APPLIANCE_LAVATRICE,
    _Mind_CATEGORY_APPLIANCE_LAVASTOVIGLIE,
    _Mind_CATEGORY_APPLIANCE_ASCIUGATRICE,
    _Mind_CATEGORY_APPLIANCE_PRESA_MULTIMEDIALE,
    _Mind_CATEGORY_APPLIANCE_COLONNETTA_TESLA,
    _Mind_CATEGORY_APPLIANCE_IMPIANTO,
    _Mind_MACRO_CATEGORY_IRRIGATION,
    _Mind_CATEGORY_IRRIGATION_PUMP,
    _Mind_MACRO_CATEGORY_ALARM,
    _Mind_CATEGORY_ALARM_SIREN,
    _Mind_MACRO_CATEGORY_GATE,
    _Mind_CATEGORY_GATE_CARRAIO,
    _Mind_CATEGORY_GATE_PEDONALE,
    _Mind_CATEGORY_GATE_GARAGE,
    _Mind_MACRO_CATEGORY_VALVE,
    _Mind_CATEGORY_VALVE_WATER_POMPA_RICIRCOLO,
    _Mind_CATEGORY_VALVE_WATER,
    _Mind_CATEGORY_VALVE_GAS,
    _Mind_MACRO_CATEGORY_SOCKET,
    _Mind_CATEGORY_SOCKET_16A,
    _Mind_CATEGORY_SOCKET_5A,
    _Mind_MACRO_CATEGORY_MULTIMEDIA,
    _Mind_MACRO_CATEGORY_MULTIMEDIA_HARMONY,
    _Mind_MACRO_CATEGORY_MULTIMEDIA_MUSIC,
    _Mind_CATEGORY_SHUTTER_PROJECTION_SCREEN,
    _Mind_CATEGORY_HARMONY_MULTIMEDIA,
    _Mind_CATEGORY_MULTIMEDIA_SONOS,
    _Mind_CATEGORY_INTERCOM,
    _Mind_CATEGORY_SOUND_MIND,
    _Mind_MACRO_CATEGORY_HEATING_COOLING,
    _Mind_MACRO_CATEGORY_IMPIANTI,
    _Mind_MACRO_CATEGORY_TERMINAL,
    _Mind_CATEGORY_HEATING_COOLING_THERMOSTAT,
    _Mind_CATEGORY_HEATING_COOLING_CALDAIA,
    _Mind_CATEGORY_HEATING_COOLING_POMPA_CALORE,
    _Mind_CATEGORY_HEATING_COOLING_FLOOR_HEATING,
    _Mind_CATEGORY_HEATING_COOLING_FAN_COIL,
    _Mind_CATEGORY_HEATING_COOLING_COOLING_FAN,
    _Mind_CATEGORY_HEATING_COOLING_HARMONY_SPLIT,
    _Mind_CATEGORY_HEATING_COOLING_TERMOSIFONE,
    _Mind_CATEGORY_HEATING_COOLING_HARMONY_AIR_CONDITIONER,
    _Mind_MACRO_CATEGORY_FLOODING,
    _Mind_CATEGORY_FLOODING_SENSOR,
    _Mind_MACRO_CATEGORY_SECURITY,
    _Mind_CATEGORY_SECURITY_SISTEM_GENERIC,
    _Mind_VIRTUAL_CATEGORY_MOMENT_AUTO,
    _Mind_VIRTUAL_CATEGORY_MOMENT_MANUAL,
    _Mind_VIRTUAL_CATEGORY_MOMENT_CINEMA,
    _Mind_VIRTUAL_CATEGORY_MOMENT_GIOCO,
    _Mind_VIRTUAL_CATEGORY_MOMENT_NINNANANNA,
    _Mind_VIRTUAL_CATEGORY_MOMENT_NINNANANNA_SERVICE_OVERRRIDABLE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_NINNANANNA_SERVICE_NOT_OVERRRIDABLE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_NANNA,
    _Mind_VIRTUAL_CATEGORY_MOMENT_NANNA_SERVICE_OVERRRIDABLE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_NANNA_SERVICE_NOT_OVERRRIDABLE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_CENA,
    _Mind_VIRTUAL_CATEGORY_MOMENT_CENA_SERVICE_OVERRRIDABLE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_CENA_SERVICE_NOT_OVERRRIDABLE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_PRANZO,
    _Mind_VIRTUAL_CATEGORY_MOMENT_PRANZO_SERVICE_OVERRRIDABLE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_PRANZO_SERVICE_NOT_OVERRRIDABLE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_CUCINO,
    _Mind_VIRTUAL_CATEGORY_MOMENT_COLAZIONE,
    _Mind_VIRTUAL_CATEGORY_MOMENT_RELAX,
    _Mind_VIRTUAL_CATEGORY_MOMENT_FESTA,
    _Mind_VIRTUAL_CATEGORY_MOMENT_SVEGLIA,
    _Mind_VIRTUAL_CATEGORY_SOUND,
    _Mind_VIRTUAL_CATEGORY_POWER_CONSUMPTION,
    _Mind_VIRTUAL_CATEGORY_DEACTIVABLE_ITEM
};

extern c_metaObject __Mind_ConfigurationType__load (c_base base);
enum _Mind_ConfigurationType {
    _Mind_CONFIGURATION_TYPE_DEFAULT,
    _Mind_CONFIGURATION_TYPE_PREFERRED,
    _Mind_CONFIGURATION_TYPE_LEARNED
};

extern c_metaObject __Mind_VirtualItemLocation__load (c_base base);
enum _Mind_VirtualItemLocation {
    _Mind_VIRTUAL_ITEM_LOCATION_CURRENT_AMBIENCE,
    _Mind_VIRTUAL_ITEM_LOCATION_CURRENT_AMBIENCE_NEIGHBORHOOD,
    _Mind_VIRTUAL_ITEM_LOCATION_CURRENT_ROOM,
    _Mind_VIRTUAL_ITEM_LOCATION_CURRENT_FLOOR,
    _Mind_VIRTUAL_ITEM_LOCATION_HOUSE,
    _Mind_VIRTUAL_ITEM_LOCATION_AMBIENCE_WITH_PEOPLE
};

extern c_metaObject __Mind_NotificationType__load (c_base base);
enum _Mind_NotificationType {
    _Mind_NOTIFICATION_TYPE_EMERGENCY,
    _Mind_NOTIFICATION_TYPE_ALERT,
    _Mind_NOTIFICATION_TYPE_INFO
};

extern c_metaObject __Mind_NotificationResponseType__load (c_base base);
enum _Mind_NotificationResponseType {
    _Mind_NOTIFICATION_RESPONSE_YES,
    _Mind_NOTIFICATION_RESPONSE_NO,
    _Mind_NOTIFICATION_RESPONSE_CANCEL
};

extern c_metaObject __Mind_NotificationSubtype__load (c_base base);
enum _Mind_NotificationSubtype {
    _Mind_NOTIFICATION_SUBTYPE_EMERGENCY_FLOODING,
    _Mind_NOTIFICATION_SUBTYPE_EMERGENCY_CO,
    _Mind_NOTIFICATION_SUBTYPE_EMERGENCY_DISCONNECTED,
    _Mind_NOTIFICATION_SUBTYPE_EMERGENCY_POWER_DOWN,
    _Mind_NOTIFICATION_SUBTYPE_EMERGENCY_FAILED_CHECKIN,
    _Mind_NOTIFICATION_SUBTYPE_EMERGENCY_HELP,
    _Mind_NOTIFICATION_SUBTYPE_ALERT_POWER_THRESHOLD_REACHED,
    _Mind_NOTIFICATION_SUBTYPE_ALERT_APPLIANCES_ON_WHILE_AWAY,
    _Mind_NOTIFICATION_SUBTYPE_ALERT_PEOPLE_DETECTED_OUTSIDE,
    _Mind_NOTIFICATION_SUBTYPE_ALERT_DOORBELL_WHILE_HOLIDAY,
    _Mind_NOTIFICATION_SUBTYPE_ALERT_DOORBELL,
    _Mind_NOTIFICATION_SUBTYPE_INFO_POWER_ANOMALY,
    _Mind_NOTIFICATION_SUBTYPE_INFO_SETTINGS_UPDATED_BY_SYSTEM,
    _Mind_NOTIFICATION_SUBTYPE_INFO_POWER_THRESHOLD_CLOSE,
    _Mind_NOTIFICATION_SUBTYPE_INFO_AIR_QUALITY_ALERT,
    _Mind_NOTIFICATION_SUBTYPE_INFO_UNKNOWN_PERSON_DETECTED,
    _Mind_NOTIFICATION_SUBTYPE_INFO_CHECKIN_SUCCESSFUL,
    _Mind_NOTIFICATION_SUBTYPE_MOVE_TO_HOLIDAY
};

#undef OS_API
#endif
