#ifndef _COMMONS_H_
#define _COMMONS_H_

#include <dds/core/ddscore.hpp>

namespace Mind
{
    OSPL_ENUM HouseMode {
        HOUSE_MODE_AWAY,
        HOUSE_MODE_HOLIDAY,
        HOUSE_MODE_DAY,
        HOUSE_MODE_NIGHT,
        HOUSE_MODE_GUEST,
        HOUSE_MODE_SETUP
    };

    OSPL_ENUM TemperatureMode {
        TEMPERATURE_MODE_NONE,
        TEMPERATURE_MODE_SUMMER,
        TEMPERATURE_MODE_WINTER
    };

    OSPL_ENUM NotificationSetting {
        SECURITY_NOTIFICATION_SETTING_NONE,
        SECURITY_NOTIFICATION_SETTING_SNS_PLUS_LED,
        SECURITY_NOTIFICATION_SETTING_SNS_PLUS_LED_PLUS_ALARM
    };

    OSPL_ENUM NightAlarmSetting {
        NIGHT_ALARM_SETTING_NONE,
        NIGHT_ALARM_SETTING_FACE_RECOGNITION,
        NIGHT_ALARM_SETTING_LOGIC,
        NIGHT_ALARM_SETTING_VOLUMETRIC
    };

    OSPL_ENUM AmbienceType {
        AMBIENCE_TYPE_ENTRANCE,
        AMBIENCE_TYPE_CORRIDOR,
        AMBIENCE_TYPE_LIVING_ROOM,
        AMBIENCE_TYPE_DINING_ROOM,
        AMBIENCE_TYPE_KITCHEN,
        AMBIENCE_TYPE_PANTRY,
        AMBIENCE_TYPE_BATHROOM,
        AMBIENCE_TYPE_DRESSINGR_ROOM,
        AMBIENCE_TYPE_BEDROOM,
        AMBIENCE_TYPE_BEDROOM_CHILDREN,
        AMBIENCE_TYPE_WARDROBE,
        AMBIENCE_TYPE_CELLAR,
        AMBIENCE_TYPE_GARAGE,
        AMBIENCE_TYPE_TECHNICAL_ROOM,
        AMBIENCE_TYPE_CATCHALL,
        AMBIENCE_TYPE_UNDERSTAIRS,
        AMBIENCE_TYPE_TERRACE,
        AMBIENCE_TYPE_VERANDA,
        AMBIENCE_TYPE_GYM,
        AMBIENCE_TYPE_SPA,
        AMBIENCE_TYPE_PLAYROOM,
        AMBIENCE_TYPE_CINEMA,
        AMBIENCE_TYPE_LAUDRY,
        AMBIENCE_TYPE_OFFICE,
        AMBIENCE_TYPE_CAVEAU,
        AMBIENCE_TYPE_STAIRS,
        AMBIENCE_TYPE_GARDEN
    };

    OSPL_ENUM SmartCommandType {
        SMART_COMMAND_LIGHTS,
        SMART_COMMAND_SHUTTERS,
        SMART_COMMAND_VENEZIANE,
        SMART_COMMAND_SCURI,
        SMART_COMMAND_GRATE,
        SMART_COMMAND_MULTIMEDIA,
        SMART_COMMAND_MUSICA,
        SMART_COMMAND_TEMPERATURE,
        SMART_COMMAND_WINDOWS,
        SMART_COMMAND_POWER_CONSUMPTION
    };

    OSPL_ENUM StateName {
        STATE_SETUP,
        STATE_AWAY,
        STATE_HOLIDAY,
        STATE_CHECKIN,
        STATE_ALARMFROMNIGHT,
        STATE_ALARMFROMCHECKIN,
        STATE_DAY,
        STATE_CHECKOUT,
        STATE_CHECKOUT_GUEST,
        STATE_CHECKOUT_HOLIDAY,
        STATE_GUEST,
        STATE_NIGHT
    };

    OSPL_ENUM Category {
        CATEGORY_NONE,
        CATEGORY_HOUSE,
        CATEGORY_FLOOR,
        CATEGORY_ROOM,
        CATEGORY_AMBIENCE,
        CATEGORY_MOBILE,
        CATEGORY_HOUSE_TABLET,
        CATEGORY_MIND_STREAMING,
        MACRO_CATEGORY_AIR_CLEANING,
        CATEGORY_AIR_CLEANING_VMC,
        CATEGORY_AIR_CLEANING_CAPPAASPIRAZIONE,
        CATEGORY_AIR_CLEANING_EXTRACTOR_FAN,
        CATEGORY_LIGHT,
        CATEGORY_LIGHT_DIMMABLE,
        CATEGORY_LIGHT_DIMMABLE_FILTER,
        CATEGORY_LIGHT_DIMMABLE_MIND,
        CATEGORY_LIGHT_RGBW_MIND,
        MACRO_CATEGORY_LIGHT_ALL,
        MACRO_CATEGORY_LIGHT_INTERNAL,
        MACRO_CATEGORY_LIGHT_EXTERNAL,
        MACRO_CATEGORY_LIGHT_MAIN,
        MACRO_CATEGORY_LIGHT_SOFT,
        MACRO_CATEGORY_LIGHT_SERVICE,
        MACRO_CATEGORY_LIGHT_STAIR,
        CATEGORY_INPUT_SWITCH,
        CATEGORY_INPUT_BUTTON,
        CATEGORY_INPUT_SHUTTER_BUTTON,
        MACRO_CATEGORY_INPUT,
        CATEGORY_CONTACT_DOOR,
        CATEGORY_CONTACT_WINDOW,
        CATEGORY_CONTACT_TAMPER,
        CATEGORY_CONTACT_PIR,
        MACRO_CATEGORY_CONTACT,
        MACRO_CATEGORY_SHUTTER,
        MACRO_CATEGORY_EXTERNAL_SHUTTER,
        CATEGORY_EXTERNAL_SHUTTER_ROLLER_SHUTTER,
        CATEGORY_EXTERNAL_SHUTTER_SCURO,
        CATEGORY_EXTERNAL_SHUTTER_FRANGISOLE,
        MACRO_CATEGORY_INTERNAL_SHUTTER,
        CATEGORY_INTERNAL_SHUTTER_BLINDS,
        CATEGORY_INTERNAL_SHUTTER_VENEZIANA,
        MACRO_CATEGORY_SECURITY_SHUTTER,
        CATEGORY_SECURITY_SHUTTER_GRATA,
        MACRO_CATEGORY_APPLIANCE,
        CATEGORY_APPLIANCE_FORNO,
        CATEGORY_APPLIANCE_FORNO_MICROONDE,
        CATEGORY_APPLIANCE_FRIGO,
        CATEGORY_APPLIANCE_FREEZER,
        CATEGORY_APPLIANCE_CANTINA_VINI,
        CATEGORY_APPLIANCE_MACCHINA_CAFFE,
        CATEGORY_APPLIANCE_CAPPA,
        CATEGORY_APPLIANCE_PIANO_COTTURA,
        CATEGORY_APPLIANCE_LAVATRICE,
        CATEGORY_APPLIANCE_LAVASTOVIGLIE,
        CATEGORY_APPLIANCE_ASCIUGATRICE,
        CATEGORY_APPLIANCE_PRESA_MULTIMEDIALE,
        CATEGORY_APPLIANCE_COLONNETTA_TESLA,
        CATEGORY_APPLIANCE_IMPIANTO,
        MACRO_CATEGORY_IRRIGATION,
        CATEGORY_IRRIGATION_PUMP,
        MACRO_CATEGORY_ALARM,
        CATEGORY_ALARM_SIREN,
        MACRO_CATEGORY_GATE,
        CATEGORY_GATE_CARRAIO,
        CATEGORY_GATE_PEDONALE,
        CATEGORY_GATE_GARAGE,
        MACRO_CATEGORY_VALVE,
        CATEGORY_VALVE_WATER_POMPA_RICIRCOLO,
        CATEGORY_VALVE_WATER,
        CATEGORY_VALVE_GAS,
        MACRO_CATEGORY_SOCKET,
        CATEGORY_SOCKET_16A,
        CATEGORY_SOCKET_5A,
        MACRO_CATEGORY_MULTIMEDIA,
        MACRO_CATEGORY_MULTIMEDIA_HARMONY,
        MACRO_CATEGORY_MULTIMEDIA_MUSIC,
        CATEGORY_SHUTTER_PROJECTION_SCREEN,
        CATEGORY_HARMONY_MULTIMEDIA,
        CATEGORY_MULTIMEDIA_SONOS,
        CATEGORY_INTERCOM,
        CATEGORY_SOUND_MIND,
        MACRO_CATEGORY_HEATING_COOLING,
        MACRO_CATEGORY_IMPIANTI,
        MACRO_CATEGORY_TERMINAL,
        CATEGORY_HEATING_COOLING_THERMOSTAT,
        CATEGORY_HEATING_COOLING_CALDAIA,
        CATEGORY_HEATING_COOLING_POMPA_CALORE,
        CATEGORY_HEATING_COOLING_FLOOR_HEATING,
        CATEGORY_HEATING_COOLING_FAN_COIL,
        CATEGORY_HEATING_COOLING_COOLING_FAN,
        CATEGORY_HEATING_COOLING_HARMONY_SPLIT,
        CATEGORY_HEATING_COOLING_TERMOSIFONE,
        CATEGORY_HEATING_COOLING_HARMONY_AIR_CONDITIONER,
        MACRO_CATEGORY_FLOODING,
        CATEGORY_FLOODING_SENSOR,
        MACRO_CATEGORY_SECURITY,
        CATEGORY_SECURITY_SISTEM_GENERIC,
        VIRTUAL_CATEGORY_MOMENT_AUTO,
        VIRTUAL_CATEGORY_MOMENT_MANUAL,
        VIRTUAL_CATEGORY_MOMENT_CINEMA,
        VIRTUAL_CATEGORY_MOMENT_GIOCO,
        VIRTUAL_CATEGORY_MOMENT_NINNANANNA,
        VIRTUAL_CATEGORY_MOMENT_NINNANANNA_SERVICE_OVERRRIDABLE,
        VIRTUAL_CATEGORY_MOMENT_NINNANANNA_SERVICE_NOT_OVERRRIDABLE,
        VIRTUAL_CATEGORY_MOMENT_NANNA,
        VIRTUAL_CATEGORY_MOMENT_NANNA_SERVICE_OVERRRIDABLE,
        VIRTUAL_CATEGORY_MOMENT_NANNA_SERVICE_NOT_OVERRRIDABLE,
        VIRTUAL_CATEGORY_MOMENT_CENA,
        VIRTUAL_CATEGORY_MOMENT_CENA_SERVICE_OVERRRIDABLE,
        VIRTUAL_CATEGORY_MOMENT_CENA_SERVICE_NOT_OVERRRIDABLE,
        VIRTUAL_CATEGORY_MOMENT_PRANZO,
        VIRTUAL_CATEGORY_MOMENT_PRANZO_SERVICE_OVERRRIDABLE,
        VIRTUAL_CATEGORY_MOMENT_PRANZO_SERVICE_NOT_OVERRRIDABLE,
        VIRTUAL_CATEGORY_MOMENT_CUCINO,
        VIRTUAL_CATEGORY_MOMENT_COLAZIONE,
        VIRTUAL_CATEGORY_MOMENT_RELAX,
        VIRTUAL_CATEGORY_MOMENT_FESTA,
        VIRTUAL_CATEGORY_MOMENT_SVEGLIA,
        VIRTUAL_CATEGORY_SOUND,
        VIRTUAL_CATEGORY_POWER_CONSUMPTION,
        VIRTUAL_CATEGORY_DEACTIVABLE_ITEM
    };

    OSPL_ENUM ConfigurationType {
        CONFIGURATION_TYPE_DEFAULT,
        CONFIGURATION_TYPE_PREFERRED,
        CONFIGURATION_TYPE_LEARNED
    };

    OSPL_ENUM VirtualItemLocation {
        VIRTUAL_ITEM_LOCATION_CURRENT_AMBIENCE,
        VIRTUAL_ITEM_LOCATION_CURRENT_AMBIENCE_NEIGHBORHOOD,
        VIRTUAL_ITEM_LOCATION_CURRENT_ROOM,
        VIRTUAL_ITEM_LOCATION_CURRENT_FLOOR,
        VIRTUAL_ITEM_LOCATION_HOUSE,
        VIRTUAL_ITEM_LOCATION_AMBIENCE_WITH_PEOPLE
    };

    OSPL_ENUM NotificationType {
        NOTIFICATION_TYPE_EMERGENCY,
        NOTIFICATION_TYPE_ALERT,
        NOTIFICATION_TYPE_INFO
    };

    OSPL_ENUM NotificationResponseType {
        NOTIFICATION_RESPONSE_YES,
        NOTIFICATION_RESPONSE_NO,
        NOTIFICATION_RESPONSE_CANCEL
    };

    OSPL_ENUM NotificationSubtype {
        NOTIFICATION_SUBTYPE_EMERGENCY_FLOODING,
        NOTIFICATION_SUBTYPE_EMERGENCY_CO,
        NOTIFICATION_SUBTYPE_EMERGENCY_DISCONNECTED,
        NOTIFICATION_SUBTYPE_EMERGENCY_POWER_DOWN,
        NOTIFICATION_SUBTYPE_EMERGENCY_FAILED_CHECKIN,
        NOTIFICATION_SUBTYPE_EMERGENCY_HELP,
        NOTIFICATION_SUBTYPE_ALERT_POWER_THRESHOLD_REACHED,
        NOTIFICATION_SUBTYPE_ALERT_APPLIANCES_ON_WHILE_AWAY,
        NOTIFICATION_SUBTYPE_ALERT_PEOPLE_DETECTED_OUTSIDE,
        NOTIFICATION_SUBTYPE_ALERT_DOORBELL_WHILE_HOLIDAY,
        NOTIFICATION_SUBTYPE_ALERT_DOORBELL,
        NOTIFICATION_SUBTYPE_INFO_POWER_ANOMALY,
        NOTIFICATION_SUBTYPE_INFO_SETTINGS_UPDATED_BY_SYSTEM,
        NOTIFICATION_SUBTYPE_INFO_POWER_THRESHOLD_CLOSE,
        NOTIFICATION_SUBTYPE_INFO_AIR_QUALITY_ALERT,
        NOTIFICATION_SUBTYPE_INFO_UNKNOWN_PERSON_DETECTED,
        NOTIFICATION_SUBTYPE_INFO_CHECKIN_SUCCESSFUL,
        NOTIFICATION_SUBTYPE_MOVE_TO_HOLIDAY
    };

}

#endif /* _COMMONS_H_ */
